### ISSUE TITLE
Game won't let me switch to another window

### ISSUE THREAD

**Issue by SubhadeepG** [seanpringle/factropy#42]
I am using windows 10. The game won't let to switch to another window (like the browser) using alt + tab. I also found no option in the menu to disable fullscreen mode. This means I am stuck in the game until I quit. The game should atleast have a window mode option in the menu.

**Comment by seanpringle** [comment]
Thanks for the bug report.

Until the menu is improved, fullscreen and window size can be controlled at startup: https://github.com/seanpringle/factropy/wiki/Configuration

**Comment by seanpringle** [comment]
Notes on this now I have access to a Windows 10 machine:

* Default _fullscreen+vsync_ works for game-play on Windows but blocks Alt-Tab window switching
* Switching to _borderless+fullscreen+vsync_ allows Alt-Tab, but vsync stops working and tearing can appear
  * Root cause appears to be Windows turns off DWM compositing for borderless windows of exactly fullscreen resolution
    * Compositing takes the place of vsync to eliminate tearing
  * GLFW doesn't account for that and leaves vsync off even if it's a requested hint
    * https://github.com/glfw/glfw/issues/1267 seems related
  * It can be faked by using a borderless window with a size 1 pixel larger than the screen resolution which causes DWM compositing to kick in

So currently on the dev branch on Windows:

* If vsync or compositing doesn't matter:
  * `factropy.exe --borderless`
  * Same thing works with driver-level vsync
* No tearing with taskbar over the window:
  * `factropy.exe --width 1920 --height 1080`  
* No tearing with window over the taskbar:
  * `factropy.exe --borderless --width 1920 --height 1081`  

Options:

* Make --borderless default on Windows
* Update Raylib to see if recent fixes handle GLFW differently

**Comment by seanpringle** [comment]
Appears fixed as a side effect of the SDL conversion.
